/*
 * generated by Xtext 2.16.0
 */
package org.sysadl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.sysadl.SysADLRuntimeModule
import org.sysadl.SysADLStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SysADLIdeSetup extends SysADLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SysADLRuntimeModule, new SysADLIdeModule))
	}
	
}
