/*
 * generated by Xtext 2.10.0
 */
package br.consiste.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSysADLScopeProvider extends DelegatingScopeProvider {
}
