/*
 * generated by Xtext 2.10.0
 */
package br.consiste.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import sysADL_Sintax.grammar.ui.internal.GrammarActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SysADLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GrammarActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GrammarActivator.getInstance().getInjector(GrammarActivator.BR_CONSISTE_SYSADL);
	}
	
}
