/*
 * generated by Xtext 2.10.0
 */
package br.consiste.parser.antlr;

import br.consiste.parser.antlr.internal.InternalSysADLParser;
import br.consiste.services.SysADLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SysADLParser extends AbstractAntlrParser {

	@Inject
	private SysADLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSysADLParser createParser(XtextTokenStream stream) {
		return new InternalSysADLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public SysADLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SysADLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
