/**
 * generated by Xtext 2.10.0
 */
package br.consiste.validation;

import br.consiste.validation.AbstractSysADLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SysADLValidator extends AbstractSysADLValidator {
}
