/**
 * generated by Xtext 2.10.0
 */
package br.consiste;

import br.consiste.AbstractSysADLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SysADLRuntimeModule extends AbstractSysADLRuntimeModule {
}
