/**
 * generated by Xtext 2.10.0
 */
package br.consiste;

import br.consiste.SysADLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SysADLStandaloneSetup extends SysADLStandaloneSetupGenerated {
  public static void doSetup() {
    SysADLStandaloneSetup _sysADLStandaloneSetup = new SysADLStandaloneSetup();
    _sysADLStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
