/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.eclipse.emf.common.util.EList;

import org.sysadl.AbstractComponentDef;
import org.sysadl.AbstractPortUse;

/**
 * A sample validator interface for {@link org.sysadl.AbstractComponentDef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractComponentDefValidator {
	boolean validate();

	boolean validatePorts(EList<AbstractPortUse> value);
	boolean validateLowerBound(int value);
	boolean validateUpperBound(int value);
	boolean validateComposition(EList<AbstractComponentDef> value);
}
