/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.eclipse.emf.common.util.EList;

import org.sysadl.ActionDef;
import org.sysadl.Pin;

/**
 * A sample validator interface for {@link org.sysadl.ActionUse}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActionUseValidator {
	boolean validate();

	boolean validateDefinition(ActionDef value);
	boolean validatePinIn(EList<Pin> value);
}
