/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.eclipse.emf.common.util.EList;

import org.sysadl.AbstractActivityDef;
import org.sysadl.ActivityBody;

/**
 * A sample validator interface for {@link org.sysadl.ActivityDef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityDefValidator {
	boolean validate();

	boolean validateBody(ActivityBody value);
	boolean validateAbstractActivity(EList<AbstractActivityDef> value);
}
