/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.eclipse.emf.common.util.EList;

import org.sysadl.ActionUse;
import org.sysadl.ActivityRelation;
import org.sysadl.DataObject;

/**
 * A sample validator interface for {@link org.sysadl.ActivityBody}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityBodyValidator {
	boolean validate();

	boolean validateActions(EList<ActionUse> value);
	boolean validateFlows(EList<ActivityRelation> value);
	boolean validateDataObjects(EList<DataObject> value);
}
