/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.eclipse.emf.common.util.EList;

import org.sysadl.ActivityDelegation;
import org.sysadl.BehaviorDef;
import org.sysadl.ConstraintUse;
import org.sysadl.DataDef;
import org.sysadl.Pin;

/**
 * A sample validator interface for {@link org.sysadl.BehaviorDef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BehaviorDefValidator {
	boolean validate();

	boolean validateInParameters(EList<Pin> value);
	boolean validateOutParameters(EList<Pin> value);
	boolean validateBehaviorDefs(EList<BehaviorDef> value);
	boolean validateDataDefs(EList<DataDef> value);
	boolean validateConstraints(EList<ConstraintUse> value);
	boolean validateDelegations(EList<ActivityDelegation> value);
}
