/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.sysadl.Expression;

/**
 * A sample validator interface for {@link org.sysadl.ConditionalTestExpression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConditionalTestExpressionValidator {
	boolean validate();

	boolean validateOp1(Expression value);
	boolean validateOp2(Expression value);
	boolean validateOp3(Expression value);
}
