/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.eclipse.emf.common.util.EList;

import org.sysadl.AbstractConnectorDef;
import org.sysadl.Configuration;
import org.sysadl.Flow;
import org.sysadl.PortUse;

/**
 * A sample validator interface for {@link org.sysadl.ConnectorDef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConnectorDefValidator {
	boolean validate();

	boolean validatePorts(EList<PortUse> value);
	boolean validateFlows(EList<Flow> value);
	boolean validateComposite(Configuration value);
	boolean validateAbstractConnector(AbstractConnectorDef value);
}
