/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.sysadl.EnumLiteralValue;
import org.sysadl.Enumeration;

/**
 * A sample validator interface for {@link org.sysadl.EnumValueLiteralExpression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EnumValueLiteralExpressionValidator {
	boolean validate();

	boolean validateEnumValue(EnumLiteralValue value);
	boolean validate_enum(Enumeration value);
}
