/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.sysadl.Enumeration;

/**
 * A sample validator interface for {@link org.sysadl.EnumLiteralValue}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EnumLiteralValueValidator {
	boolean validate();

	boolean validateEnum(Enumeration value);
	boolean validateName(String value);
}
