/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.eclipse.emf.common.util.EList;

import org.sysadl.ElseStatement;
import org.sysadl.IfStatement;

/**
 * A sample validator interface for {@link org.sysadl.IfBlockStatement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IfBlockStatementValidator {
	boolean validate();

	boolean validateMain_if(IfStatement value);
	boolean validateParalel_ifs(EList<IfStatement> value);
	boolean validateSequential_ifs(EList<IfStatement> value);
	boolean validateFinal(ElseStatement value);
	boolean validateElse(ElseStatement value);
}
