/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.sysadl.AffixOperator;
import org.sysadl.LeftHandSide;

/**
 * A sample validator interface for {@link org.sysadl.IncrementOrDecrementExpression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IncrementOrDecrementExpressionValidator {
	boolean validate();

	boolean validateOperand(LeftHandSide value);
	boolean validateOperator(AffixOperator value);
}
