/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.sysadl.ArrayIndex;
import org.sysadl.NameExpression;
import org.sysadl.PrimaryExpression;

/**
 * A sample validator interface for {@link org.sysadl.LeftHandSide}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LeftHandSideValidator {
	boolean validate();

	boolean validateTarget(NameExpression value);
	boolean validateIndex(ArrayIndex value);
	boolean validateFeature(PrimaryExpression value);
}
