/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.sysadl.NamedElement;

/**
 * A sample validator interface for {@link org.sysadl.NameExpression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NameExpressionValidator {
	boolean validate();

	boolean validateCite(NamedElement value);
}
