/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.eclipse.emf.common.util.EList;

import org.sysadl.ElementDef;
import org.sysadl.Style;

/**
 * A sample validator interface for {@link org.sysadl.Package}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PackageValidator {
	boolean validate();

	boolean validateImports(EList<org.sysadl.Package> value);
	boolean validateImportedDefinitions(EList<ElementDef> value);
	boolean validateDefinitions(EList<ElementDef> value);
	boolean validateAppliedStyle(EList<Style> value);

	boolean validateAppliedStyle(Style value);
}
