/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.sysadl.ProtocolAlternativeType;
import org.sysadl.ProtocolBody;
import org.sysadl.ProtocolBodyInternal;
import org.sysadl.ProtocolControl;

/**
 * A sample validator interface for {@link org.sysadl.ProtocolBody}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProtocolBodyValidator {
	boolean validate();

	boolean validateRecControl(ProtocolControl value);
	boolean validateBody(ProtocolBodyInternal value);
	boolean validateRecursive(ProtocolBody value);
	boolean validateRecType(ProtocolAlternativeType value);
}
