/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.eclipse.emf.common.util.EList;

import org.sysadl.ElementDef;
import org.sysadl.Requirement;

/**
 * A sample validator interface for {@link org.sysadl.Requirement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RequirementValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateText(String value);
	boolean validateDerive(EList<Requirement> value);
	boolean validateComposition(EList<Requirement> value);
	boolean validateSatisfiedBy(EList<ElementDef> value);
}
