/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.sysadl.SequenceElements;
import org.sysadl.TypeDef;

/**
 * A sample validator interface for {@link org.sysadl.SequenceConstructionExpression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SequenceConstructionExpressionValidator {
	boolean validate();

	boolean validateType(TypeDef value);
	boolean validateElements(SequenceElements value);
}
