/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.sysadl.NaturalLiteralExpression;

/**
 * A sample validator interface for {@link org.sysadl.SequenceRange}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SequenceRangeValidator {
	boolean validate();

	boolean validateRangeLower(NaturalLiteralExpression value);
	boolean validateRangeUpper(NaturalLiteralExpression value);
}
