/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.eclipse.emf.common.util.EList;

import org.sysadl.DataDef;
import org.sysadl.Invariant;
import org.sysadl.StructuralDef;

/**
 * A sample validator interface for {@link org.sysadl.StructuralDef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StructuralDefValidator {
	boolean validate();

	boolean validateStructuralDefs(EList<StructuralDef> value);
	boolean validateDataDefs(EList<DataDef> value);
	boolean validateInvariants(EList<Invariant> value);
}
