/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.eclipse.emf.common.util.EList;

import org.sysadl.Expression;
import org.sysadl.SwitchClause;

/**
 * A sample validator interface for {@link org.sysadl.SwitchStatement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SwitchStatementValidator {
	boolean validate();

	boolean validateExpr(Expression value);
	boolean validateClauses(EList<SwitchClause> value);
}
