/**
 *
 * $Id$
 */
package org.sysadl.validation;

import org.sysadl.DimensionDef;
import org.sysadl.UnitDef;
import org.sysadl.ValueTypeDef;

/**
 * A sample validator interface for {@link org.sysadl.ValueTypeDef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ValueTypeDefValidator {
	boolean validate();

	boolean validateUnit(UnitDef value);
	boolean validateDimension(DimensionDef value);
	boolean validateSuperType(ValueTypeDef value);
}
