/*
 * generated by Xtext 2.12.0
 */
package br.consiste.ide

import br.consiste.SysADLRuntimeModule
import br.consiste.SysADLStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SysADLIdeSetup extends SysADLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SysADLRuntimeModule, new SysADLIdeModule))
	}
	
}
