/*
 * generated by Xtext 2.16.0
 */
package org.sysadl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SysADLStandaloneSetup extends SysADLStandaloneSetupGenerated {

	def static void doSetup() {
		new SysADLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
